<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Cylinder inertia mecros -->
  <xacro:macro name="Cylinder_inertia" params="mass radius length">
    <!-- ixx = iyy = 1/12 m (3r^2 + l^2), izz = 1/2 m r^2 -->
    <!-- Due to the axial symmetry of the mass distribution, the off-diagonal terms of the inertia tensor vanish theoretically. -->
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      <inertia ixx="${mass/12.0*(3*radius*radius + length*length)}"
               iyy="${mass/12.0*(3*radius*radius + length*length)}"
               izz="${0.5*mass*radius*radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="leg" params="prefix parent xyz rpy
                                  thigh_length calf_length
                                  link_radius thigh_mass calf_mass foot_mass
                                  mu_static mu_dynamic">

    <!-- Thigh-->
    <link name="${prefix}_thigh">
      <visual>
        <geometry><cylinder radius="${link_radius}" length="${thigh_length}"/></geometry>
        <origin xyz="0 0 ${thigh_length/2}" rpy="0 0 0"/>
        <material name="blue"><color rgba="0 0 1 1"/></material>
      </visual>
      <collision>
        <geometry><cylinder radius="${link_radius}" length="${thigh_length}"/></geometry>
        <origin xyz="0 0 ${thigh_length/2}" rpy="0 0 0"/>
      </collision>
      <xacro:cylinder_inertia mass="${thigh_mass}" radius="${link_radius}" length="${thigh_length}"/>
    </link>

    <!-- Hip joint -->
    <joint name="${prefix}_hip_joint" type="revolute">
      <parent_link="${parent}"/>
      <child_link="${prefix}_thigh"/>
      <origin xyz="${xyz}" rpy="{rpy}"/>
      <axis xyz="0 1 0"/>
      <limit effort="30" velocity="5" lower="-1.5" upper="1.5"/>
    </joint>

    <!-- Calf -->
    <link name="${prefix}_calf">
      <visual>
        <geometry><cylinder radius="${link_radius}" length="${calf_length}"/></geometry>
        <origin xyz="0 0 ${calf_length/2}" rpy="0 0 0"/>
        <material name="green"><color rgba="0 1 0 1"/></material>
      </visual>
      <collision>
        <geometry><cylinder radius="${link_radius}" length="${calf_length}"/></geometry>
        <origin xyz="0 0 ${calf_length/2}" rpy="0 0 0"/>
      </collision>
      <xacro:cylinder_inertia mass="${calf_mass}" radius="${link_radius}" length="${calf_length}"/>
    </link>

    <!-- Knee joint -->
    <joint name="${prefix}_knee_joint" type="revolute">
      <parent link="${prefix}_thigh"/>
      <child link="${prefix}_calf"/>
      <origin xyz="0 0 ${thigh_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effor="30" velocity="5" lower="0" upper="2.6"/>
    </joint>

  <!-- Foot -->
  <!-- for a sphere, the <origin> tag is optional. -->
  <!-- e-4 means exp(-4) -->
    <link name="${prefix}_foot">
      <visual>
        <geometry><sphere radius="${foot_radius}"/></geometry>
        <material name="red"><color rgba="1 0 0 1"/></material>
      </visual>
      <collision>
        <geometry><sphere radius="${foot_radius}"/></geometry>
      </collision>
      <inertial>
        <mass value="${foot_mass}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-4" iyy="1e-4" izz="1e-4" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <!-- Ankle joint -->
    <joint name="${prefix}_ankle_fixed" type="fixed">
      <parent link="${prefix}_calf"/>
      <child link="${prefix}_foot"/>
      <origin xyz="0 0 ${calf_length}" rpy="0 0 0"/>
    </joint>

    <!-- Gazebo friction -->
    <!-- These are not static/dynamic friction coefficients.
         They represent he two friction coefficients along the local axes of the content surface (mu1, mu2). -->
    <gazebo reference="${prefix}_foot">
      <mu1>${mu_dynamic}</mu1>
      <mu2>${mu_dynamic}</mu2>
      <kp>1e5</kp><!-- spring stiffness -->
      <kd>1.5</kd><!-- damping -->
      <fdir1>1 0 0</fdir1><!-- friction direction vector -->
    </gazebo>
  </xacro:macro>
</robot>