<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:property name="leg_length" value="0.24"/>
    <xacro:property name="leg_radius" value="0.04"/>
    <xacro:property name="foot_radius" value="0.05" />

    <xacro:macro name="leg" params="upper_link_name lower_link_name foot_link_name parent x_offset y_offset">
        <link name="${upper_link_name}">
            <visual>
                <origin xyz="0 0 -${leg_length/2}" />
            
                <geometry>
                    <cylinder radius="${leg_radius}" length="${leg_length}" />
                </geometry>

                <material name="gray">
                    <color rgba="0.5 0.5 0.5 1" />
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 -${leg_length/2}" />

                <geometry>
                    <cylinder radius="${leg_radius}" length="${leg_length}" />
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 -${leg_length/2}" />
                <mass value="1.0" />
                <inertia ixx="0.0309" iyy="0.0084" izz="0.018" ixy="0" ixz="0" iyz="0" />
            </inertial>
        </link>
        <gazebo reference="${upper_link_name}">
            <selfCollide>false</selfCollide>
            <mu1>0.4</mu1>
            <mu2>0.2</mu2>
        </gazebo>

        <joint name="base_to_${upper_link_name}" type="revolute">
            <parent link="${parent}" />
            <child link="${upper_link_name}" />
            <origin rpy="0 0 0" xyz="${x_offset} ${y_offset} 0" />
            <axis xyz="1 0 0" />
            <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>
        <transmission name="${upper_link_name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${upper_link_name}_motor">
                <mechanicalReduction>1</mechanicalReduction> <!--とりあえずテストしたいだけなので、現実のギア減速やらトルクは気にしなくていい-->
            </actuator>
            <joint name="base_to_${upper_link_name}">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface> <!--とりあえずgazeboでテストしたいだけなので、力制御と速度制御は捨ておく-->
            </joint>
        </transmission>

        <link name="${lower_link_name}">
            <visual>
                <origin xyz="0 0 -${leg_length/2}" />
            
                <geometry>
                    <cylinder radius="${leg_radius}" length="${leg_length}" />
                </geometry>

                <material name="gray">
                    <color rgba="0.5 0.5 0.5 1" />
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 -${leg_length/2}" />

                <geometry>
                    <cylinder radius="${leg_radius}" length="${leg_length}" />
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 -${leg_length/2}" />
                <mass value="1.0" />
                <inertia ixx="0.0309" iyy="0.0084" izz="0.018" ixy="0" ixz="0" iyz="0" />
            </inertial>
        </link>
        <gazebo reference="${lower_link_name}">
            <selfCollide>false</selfCollide>
            <mu1>0.4</mu1>
            <mu2>0.2</mu2>
        </gazebo>

        <joint name="${upper_link_name}_to_${lower_link_name}" type="revolute">
            <parent link="${upper_link_name}" />
            <child link="${lower_link_name}" />
            <origin rpy="0 0 0" xyz="0 0 -${leg_length}" />
            <axis xyz="1 0 0" />
            <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>
        <transmission name="${lower_link_name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${lower_link_name}_motor">
                <mechanicalReduction>1</mechanicalReduction> <!--とりあえずテストしたいだけなので、現実のギア減速やらトルクは気にしなくていい-->
            </actuator>
            <joint name="${upper_link_name}_to_${lower_link_name}">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface> <!--とりあえずgazeboでテストしたいだけなので、力制御と速度制御は捨ておく-->
            </joint>
        </transmission>

        <link name="${foot_link_name}">
            <visual>
                <origin xyz="0 0 -${foot_radius}" />

                <geometry>
                    <sphere radius="${foot_radius}" />
                </geometry>

                <material name="gray">
                    <color rgba="0.5 0.5 0.5 1" />
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 -${foot_radius}" />

                <geometry>
                    <sphere radius="${foot_radius}" />
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 -${foot_radius}" />
                <mass value="0.5" />
                <inertia ixx="0.00175" iyy="0.00175" izz="0.0005" ixy="0" ixz="0" iyz="0" />
            </inertial>
        </link>
        <gazebo reference="${foot_link_name}">
            <selfCollide>false</selfCollide>
            <mu1>0.8</mu1>
            <mu2>1.0</mu2>
        </gazebo>

        <joint name="${lower_link_name}_to_${foot_link_name}" type="fixed">
            <parent link="${lower_link_name}" />
            <child link="${foot_link_name}" />
            <origin rpy="0 0 0" xyz="0 0 -${leg_length}" />
        </joint>
    </xacro:macro>
</robot>